### ISSUE TITLE
conversion_service/activate_account can't handle multiple concurrent calls

### ISSUE THREAD

**Issue by JonasWijne** [threefoldfoundation/tft-stellar#36]
When i convert multiple accounts i get a 400

**Comment by DylanVerstraete** [comment]
This is due to Horizon server automatically incrementing account sequence. If you start making these transactions async the increments will be submitted out of order to Horizon.

**Comment by robvanmieghem** [comment]
Another option is to have multiple accounts sending the tokens, this is not only needed for this but also for the transaction funding service.
1 master account can first send the tokens to a slave account that sends them to the needed one

Requirements:
- [ ] [Possibility for a wallet to know if it's usedsequence number  has already been submittted to the Stellar network](https://github.com/threefoldtech/jumpscaleX_libs/issues/164)

**Comment by robvanmieghem** [comment]
forget my previous comment, #119 should fix this

**Comment by robvanmieghem** [comment]
going to do it differently, since the transaction funding service needs the wallets to be left alone for a while and the amounts are very low, the slave wallets are a very good solution. For the activation, this can be done sequentially on the server without  and the amounts are higher, limiting the throughput to the the master account's ability to refund.

**Comment by robvanmieghem** [comment]
fixed in d854949d3f21e530b343f38324e89f668943c471 still have to deploy

**Comment by robvanmieghem** [comment]
deployed to testnet
