### ISSUE TITLE
error when requesting freetft from the faucet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft-stellar#86]
This address probably does not exist or does not have a trustline with the issuer of our Stellar TFT (Testnet).

**Comment by DylanVerstraete** [comment]
![Screenshot from 2020-04-09 11-21-41](https://user-images.githubusercontent.com/17138347/78879561-57606c80-7a54-11ea-870f-32844611e1fd.png)

Due to the changes made to get this deployed we created another bug, seems like the fields searchParams in the url object is now empty (because we added a # in the url)

Investigating now

**Comment by DylanVerstraete** [comment]
Fixed in: https://github.com/threefoldfoundation/tft-stellar/commit/d1dc033d23e90c6c8ce7292fc5783fab7626d123
